# Generated by Django 4.2.2 on 2023-06-07 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(default='hsa/0000/A', max_length=300)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('nationality', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMAlE', 'Female'), ('OTHERS', 'Others')], default='MALE', max_length=10)),
                ('image', models.ImageField(default='images/pic.png', upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
