# Generated by Django 4.2.3 on 2023-07-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_amountpaid_levels_passwordresets_students_and_more'),
        ('default', '0007_students_alter_amountpaid_student_delete_userprofile'),
    ]

    operations = [
    ]
